### ISSUE TITLE
Various Kinds of Point Clouds

### ISSUE THREAD

**Issue by mgswartz1** [ASPRSorg/LAS#139]
### What is the issue about?

Committee efforts

### Issue description

For the upcoming 1.5 specification, we suggest some method to differentiate active sensors from a passive sensor derived product.  We have started to see 
LPC – Lidar Point Cloud
PPC – Photogrammetrically derived Point Cloud
TPC – Terrestrial scanner Point Cloud
MPC – Mobile Point Cloud
BPC _ Bathymetric Point Cloud
And others types of Point Clouds

Where each type of Point Cloud has characteristics that separate it from the others, and generally require an understanding of these characteristic for proper utilization.

**Comment by hobu** [comment]
The distinction between all of these is not as clear is it would first appear. Is a Bathymetric Point Cloud captured by a lidar different than one captured by sonar? What would you label the lidar file vs the sonar one?

I'm not supportive of baking labels into the specification. LAS was originally intended and developed to store linear model lidar data. People can use LAS to transport other data types, but most of LAS' features are oriented toward that initial intended use. This includes many of the fixed dimensions that the PDRFs mandate.

**Comment by esilvia** [comment]
@mgswartz1 We made something of an attempt at this by publishing the public registry of system identifiers, although it requires extremely active maintenance to stay relevant. I have not seen that this provides significant value to more than one or two users.

Can you provide a use case where including a more general label of this kind would provide value? Generally I agree with @hobu that the distinctions between these systems are incredibly fuzzy, particularly since some systems such as the Riegl VQ-880-G or Optech Titan perform multiple scanning modes simultaneously.

**Comment by mgswartz1** [comment]
Howard,  I agree and I am trying to find a way to differential between Active Lidar Sensor Point Clouds and the Photogrammetrically derived Point Clouds.  Too many times I have seen end users calling a Photogrammetrically derived Point Cloud as a Lidar point cloud, and treating it as such.  When we factor in the training datasets for A.I.  The differences between a LPC and a PPC are notable.  With esilvia's link to the  system identifiers I see the "Pure Generic" Any 3-band camera would suffice.  Thanks for the feedback.
